---
ansible_user: admin                # nom de l'utilisateur SSH
ansible_become_password: "{{vault_ansible_password}}"
ansible_password: "{{vault_ansible_password}}"
ansible_python_interpreter: /usr/bin/python3
