---
- name: Déployer Apache dans un conteneur Docker
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml
    

  pre_tasks:
    - name: Installer le dépôt EPEL
      package:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - wget
        - curl

    - name: Installer Docker via script officiel
      shell: curl -fsSL https://get.docker.com | sh
      args:
        warn: false

    - name: Installer Python3 et pip3
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Démarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: yes

  tasks:
    - name: Copier le fichier index.html depuis template
      template:
        src: index.html.j2
        dest: /home/admin/index.html

   - name: Créer le conteneur Apache
     docker_container:
       name: webapp
       image: httpd
       ports:
         - "80:80"
       volumes:
         - "/home/admin/index.html:/usr/local/apache2/htdocs/index.html"
       state: started
       restart_policy: always

